### ISSUE TITLE
fails to compile on ocaml 4.08

### ISSUE THREAD

**Issue by treinen** [xavierleroy/spamoracle#1]
spamoracle fails to compile on ocaml 4.08, due to the fact that -safe-string is now the default:

````
File "mail.ml", line 250, characters 36-39:
250 |     | Some txt -> fn {m with body = txt}
                                          ^^^
Error: This expression has type bytes but an expression was expected of type
         string
````

**Comment by xavierleroy** [comment]
Maybe it's time to retire SpamOracle -- I can't believe a 2002 design for a spam filter is still effective today.  But it is not my decision to take, so I updated the sources and will make a release shortly.
